// Alerts

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Auth
export const DOCTOR_REGISTER_SUCCESS = "DOCTOR_REGISTER_SUCCESS";
export const DOCTOR_REGISTER_FAIL = "DOCTOR_REGISTER_FAIL";
export const DOCTOR_USER_LOADED = "DOCTOR_USER_LOADED";
export const DOCTOR_AUTH_ERROR = "DOCTOR_AUTH_ERROR";
export const DOCTOR_LOGIN_SUCCESS = "DOCTOR_LOGIN_SUCCESS";
export const DOCTOR_LOGIN_FAIL = "DOCTOR_LOGIN_FAIL";
export const DOCTOR_LOGOUT = "DOCTOR_LOGOUT";

